#!python3
# -*- coding: utf-8 -*-
import re
import sys
sys._hfai_import = False
from hfai.client.hfai_cli import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
