[scheduler]
re_signal = 60
send_fetion = 120
default_group = 'jd_test_a100'
error_node_meta_group = "err_nodes"
rotate_num = 5

# 基础的组件
[scheduler.beater.ticks]
class = 'scheduler.base_model.Beater'
kwargs = {interval = 1000}
[scheduler.monitor.check_alive]
class = 'scheduler.base_model.monitor.Monitor'
kwargs = {check_interval = 10000}

# training 逻辑
[scheduler.assigner.training]
class = 'scheduler.modules.assigners.simple_fifo.FIFOAssigner'

[scheduler.matcher.training]
class = 'scheduler.modules.matchers.simple_fifo.FIFOMatcher'
kwargs = {reserved_memory = 24696061952, reserved_cpu = 10}

[scheduler.subscriber.training_matcher_logger]
class = 'scheduler.modules.subscribers.matcher_logger.MatcherLogger'

[scheduler.relations.training]
'beater.ticks' = ['assigner.training']
'assigner.training' = ['matcher.training']
'matcher.training' = ['subscriber.training_matcher_logger']

# jupyter 逻辑
[scheduler.assigner.jupyter]
class = 'scheduler.modules.assigners.jupyter.JupyterAssigner'
[scheduler.matcher.jupyter]
class = 'scheduler.modules.matchers.jupyter_matcher.JupyterMatcher'
[scheduler.subscriber.jupyter_matcher_logger]
class = 'scheduler.modules.subscribers.matcher_logger.MatcherLogger'

[scheduler.relations.jupyter]
'beater.ticks' = ['assigner.jupyter']
'assigner.jupyter' = ['matcher.jupyter']
'matcher.jupyter' = ['subscriber.jupyter_matcher_logger']

# bff
[scheduler.subscriber.bff_processor]
class = 'scheduler.modules.subscribers.bff.BFFProcessor'
[scheduler.relations.bff]
'matcher.training' = ['subscriber.bff_processor']
